apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eks-runner-deployment
  name: eks-runner-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-runner-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eks-runner-deployment
    spec:
      containers:
      - image: 795043606509.dkr.ecr.us-east-1.amazonaws.com/runner:eksrunner0.91
        name: eks-runner
        envFrom:
        - secretRef:
            name: runner-secret
        - configMapRef:
            name: runner-configmap
