name: Automatic Rebase
on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: v1
        FOLDER: ./
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      
