name: Automatic Rebase
on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: rebase
      run: |
        git remote -v
        git branch
        git fetch origin v1
        git checkout v1
        git rebase main
        git push -u origin v1
        
      
