name: Automatic Rebase
on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: rebase
      run: |
        git init
        git remote add rh ${{ secrets.GH_ACCESS_TOKEN }}@github.com:dchourasia/self-hosted-eks-runners.git
        git fetch --all
        git checkout v1
        git checkout main
        git rebase main
        git push -u rh main
        
      
