# This is a basic workflow to help you get started with Actions

name: AWS

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: k8s-runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: us-east-1
          role-session-name: githubaction@eks-runner
          role-skip-session-tagging: true
      - name: fetch secret from AWS using CLI
        run: aws secretsmanager get-secret-value --secret-id ADAdminSecret-test-addschange
