name: Create EKS Cluster

on:
  workflow_dispatch:


permissions:
  packages: write
  contents: read
  id-token: write
  
jobs:

  build:
    runs-on: ci360-go-runner

    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ROLE_ARN }}
        aws-region: us-east-1
        role-session-name: githubaction@eks-cluster
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v2.1
      with:
        # Version of kubectl
        version: latest
    - name: deploy to k8s
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        eksctl version
        eksctl create cluster -f k8s/cluster.yaml
